arrowParens: always
bracketSpacing: true
endOfLine: lf
htmlWhitespaceSensitivity: css
insertPragma: false
singleAttributePerLine: false
bracketSameLine: false
jsxBracketSameLine: false
jsxSingleQuote: false
printWidth: 100
proseWrap: preserve
quoteProps: as-needed
requirePragma: false
semi: false
singleQuote: true
tabWidth: 2
trailingComma: all
useTabs: false
embeddedLanguageFormatting: auto
vueIndentScriptAndStyle: false
plugins:
  - prettier-plugin-tailwindcss
