import type { EditorThemeClasses } from 'lexical'

import styles from './editor.module.css'

const theme: EditorThemeClasses = {
  blockCursor: styles.blockCursor,
  characterLimit: styles.characterLimit,
  code: styles.code,
  codeHighlight: {
    atrule: styles.tokenAttr,
    attr: styles.tokenAttr,
    boolean: styles.tokenProperty,
    builtin: styles.tokenSelector,
    cdata: styles.tokenComment,
    char: styles.tokenSelector,
    class: styles.tokenFunction,
    'class-name': styles.tokenFunction,
    comment: styles.tokenComment,
    constant: styles.tokenProperty,
    deleted: styles.tokenProperty,
    doctype: styles.tokenComment,
    entity: styles.tokenOperator,
    function: styles.tokenFunction,
    important: styles.tokenVariable,
    inserted: styles.tokenSelector,
    keyword: styles.tokenAttr,
    namespace: styles.tokenVariable,
    number: styles.tokenProperty,
    operator: styles.tokenOperator,
    prolog: styles.tokenComment,
    property: styles.tokenProperty,
    punctuation: styles.tokenPunctuation,
    regex: styles.tokenVariable,
    selector: styles.tokenSelector,
    string: styles.tokenSelector,
    symbol: styles.tokenProperty,
    tag: styles.tokenProperty,
    url: styles.tokenOperator,
    variable: styles.tokenVariable,
  },
  embedBlock: {
    base: styles.embedBlock,
    focus: styles.embedBlockFocus,
  },
  hashtag: styles.hashtag,
  heading: {
    h1: styles.h1,
    h2: styles.h2,
    h3: styles.h3,
    h4: styles.h4,
    h5: styles.h5,
    h6: styles.h6,
  },
  image: 'editor-image',
  link: styles.link,
  list: {
    listitem: styles.listItem,
    listitemChecked: styles.listItemChecked,
    listitemUnchecked: styles.listItemUnchecked,
    nested: {
      listitem: styles.nestedListItem,
    },
    olDepth: [styles.ol1, styles.ol2, styles.ol3, styles.ol4, styles.ol5],
    ul: styles.ul,
  },
  ltr: styles.ltr,
  mark: styles.mark,
  markOverlap: styles.markOverlap,
  paragraph: styles.paragraph,
  quote: styles.quote,
  rtl: styles.rtl,
  table: styles.table,
  tableAddColumns: styles.tableAddColumns,
  tableAddRows: styles.tableAddRows,
  tableCell: styles.tableCell,
  tableCellActionButton: styles.tableCellActionButton,
  tableCellActionButtonContainer: styles.tableCellActionButtonContainer,
  tableCellEditing: styles.tableCellEditing,
  tableCellHeader: styles.tableCellHeader,
  tableCellPrimarySelected: styles.tableCellPrimarySelected,
  tableCellResizer: styles.tableCellResizer,
  tableCellSelected: styles.tableCellSelected,
  tableCellSortedIndicator: styles.tableCellSortedIndicator,
  tableResizeRuler: styles.tableCellResizeRuler,
  tableSelected: styles.tableSelected,
  text: {
    bold: styles.textBold,
    code: styles.textCode,
    italic: styles.textItalic,
    strikethrough: styles.textStrikethrough,
    subscript: styles.textSubscript,
    superscript: styles.textSuperscript,
    underline: styles.textUnderline,
    underlineStrikethrough: styles.textUnderlineStrikethrough,
  },
}

export default theme
